const ROLES = {
  PROVIDER: 'provider',
  REVIEWER: 'reviewer',
  ADMIN: 'admin',
}

const REQUESTS_PROVIDERS_STATUS = {
  APPROVED_DOCUMENTATION: 'APPROVED_DOCUMENTATION',
  REJECTED_DOCUMENTATION: 'REJECTED_DOCUMENTATION',
  DOCUMENTATION_IN_REVIEW: 'DOCUMENTATION_IN_REVIEW',
}

export {
  ROLES,
  REQUESTS_PROVIDERS_STATUS,
}
